# Generated by Django 5.2.7 on 2025-10-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('SignedUp', 'Signed up'), ('DidNotSignup', "Didn't signup")], default='Pending', max_length=20),
        ),
    ]
