# Generated by Django 5.2.7 on 2025-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trial_reason_trial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(help_text='0=Monday .. 6=Sunday')),
                ('time', models.CharField(blank=True, max_length=16)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Afventer'), ('Done', 'Udført'), ('NotUsed', 'Ikke i brug'), ('NotDone', 'Ikke udført')], default='Pending', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('Pending', 'Afventer'), ('SignedUp', 'Tilmeldt'), ('DidNotSignup', 'Blev ikke meldt ind')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trial',
            name='trial_type',
            field=models.CharField(choices=[('Class', 'Hold'), ('Fitness', 'Fitness')], max_length=20),
        ),
    ]
