# Generated by Django 4.2.25 on 2025-10-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_create_ptlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptlead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
